name: churn-imbalanced-dataset

on: [push]

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install CML utility
        uses: iterative/setup-cml@v2

      - name: Install dependencies (Python, DVC, CML)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[gdrive]==3.63.0"
          # pip install cml  # si pas déjà dans requirements.txt

      - name: Configure DVC remote for Google Drive (OAuth user creds)
        run: |
          echo '${{ secrets.GDRIVE_CREDENTIALS_JSON }}' > gdrive_user_credentials.json
          dvc remote modify --local new_gdrive gdrive_user_credentials_file gdrive_user_credentials.json
          dvc remote modify --local new_gdrive gdrive_client_id "${{ secrets.GDRIVE_CLIENT_ID }}"
          dvc remote modify --local new_gdrive gdrive_client_secret "${{ secrets.GDRIVE_CLIENT_SECRET }}"

      - name: Pull data & models from DVC remote
        run: |
          dvc pull -v

      - name: Train / Evaluate model(s)
        run: |
          python script.py

      - name: Track new artifacts with DVC
        run: |
          dvc add data/ models/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.dvc models.dvc
          git commit -m "Update DVC artifacts [skip ci]" || echo "Nothing to commit"

      - name: Push data & models to DVC remote
        run: |
          dvc push -v

      - name: Generate and publish CML report
        run: |
          echo "## Metrics" > report.md
          awk 'NR%4{print "    " $0}{print ""}' metrics.txt >> report.md
          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md
          cml comment create report.md
